version: '3'
services:
  moneymanapi:
    container_name: "moneyman-api"
    build: .
    ports:
      - "8600:80"
    volumes:
      - ./Moneyman.Api/LocalDatabase.db:/app/LocalDatabase.db
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - mysql:/var/lib/mysql
      - /home/miles/dev/moneyman-api/src/Moneyman.Api/export_script.sql:/dump.sql

volumes:
  mysql: