name: .NET

on:
  push:
    branches: [ development, ci, refactor/*, feature/* ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    env:
      working-directory: ./src

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.working-directory }}
    - name: Test
      run: dotnet test Moneyman.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  /p:CoverletOutput='cobertura.xml' --no-build --verbosity normal
      working-directory: ${{ env.working-directory }}
    - name: Debug
      run: ls && echo '---' && ls src  &&  echo '---' && ls src/Moneyman.Tests
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: src/Moneyman.Tests/cobertura.xml

